type: postgres
name: analytics_postgres
connection:
  host: ${env.ANALYTICS_POSTGRES_HOST}
  port: 5432
  user: ${env.ANALYTICS_POSTGRES_USER}
  password: ${env.ANALYTICS_POSTGRES_PASSWORD}
  database: ${env.ANALYTICS_POSTGRES_DB}
