{{ config(materialized="view", tags=["product_reporting_phase1", "data_vault"]) }}

select
  event_funnel_action_hk,
  event_funnel_hashdiff as hashdiff,
  load_datetime,
  record_source,
  event_id,
  event_name,
  event_version,
  reporting_date,
  occurred_at,
  received_at,
  community_event_hk,
  community_event_business_key,
  event_funnel_action,
  surface,
  action_source,
  request_id,
  reason_key,
  capacity_state,
  previous_participation_state,
  participation_state,
  seconds_until_start_bucket,
  rank,
  visible_pct,
  visible_ms,
  duration_ms,
  privacy_class,
  consent_scope,
  subject_user_hk,
  subject_session_id,
  source_completeness_input,
  source_topic,
  source_partition,
  source_offset,
  raw_record_sha256,
  payload_sha256
from {{ ref("stg_product_reporting_event_funnel") }}
where event_funnel_action_hk is not null
