{{ config(materialized="view", tags=["product_reporting_phase1", "data_vault"]) }}

select
  together_item_hk,
  together_metadata_hashdiff as hashdiff,
  load_datetime,
  record_source,
  event_id,
  event_name,
  event_version,
  reporting_date,
  occurred_at,
  received_at,
  together_item_business_key,
  together_target_hk,
  together_target_business_key,
  linked_event_hk,
  linked_event_business_key,
  channel_hk,
  channel_business_key,
  together_action,
  activity_type,
  visibility,
  together_status,
  action_source,
  response_type,
  report_category,
  invite_count,
  response_count,
  response_latency_bucket,
  privacy_class,
  consent_scope,
  subject_user_hk,
  subject_session_id,
  source_completeness_input,
  source_topic,
  source_partition,
  source_offset,
  raw_record_sha256,
  payload_sha256
from {{ ref("stg_app_together_items") }}
where together_item_hk is not null
