{{ config(materialized="view", tags=["product_reporting_phase1", "data_vault"]) }}

select
  feed_item_hk,
  feed_event_hashdiff as hashdiff,
  load_datetime,
  record_source,
  event_id,
  event_name,
  event_version,
  reporting_date,
  occurred_at,
  received_at,
  content_business_key,
  item_type,
  feed_kind,
  feed_mode,
  surface,
  source_bucket,
  reason_key,
  candidate_set_id,
  model_version,
  feature_schema_version,
  score_bucket,
  fallback_reason,
  rollback_state,
  assignment_bucket,
  holdout_bucket,
  shadow_mode,
  occupation_cohort_key,
  interest_proxy_valence,
  position,
  page_depth,
  page_size,
  visible_duration_ms,
  visible_percent_max,
  dwell_ms,
  action_source,
  privacy_class,
  consent_scope,
  source_completeness_input,
  source_topic,
  source_partition,
  source_offset,
  raw_record_sha256,
  payload_sha256
from {{ ref("stg_product_reporting_feed_events") }}
where feed_item_hk is not null
